services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app/src:/app/src
    depends_on:
      - database
      - rabbitmq
    networks:
      - app-network

  web-proxy:
    build: ./web-proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    restart: on-failure
    networks:
      - app-network

  database:
    image: postgres:16
    env_file:
      - ./app/.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_volume:
  rabbitmq_volume:

networks:
  app-network:
    driver: bridge
