services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app/src:/app/src
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  worker-1:
    build: ./app
    command: python -m src.worker
    env_file:
      - ./app/.env
    environment:
      WORKER_ID: worker-1
    volumes:
      - ./app/src:/app/src
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
    networks:
      - app-network

  worker-2:
    build: ./app
    command: python -m src.worker
    env_file:
      - ./app/.env
    environment:
      WORKER_ID: worker-2
    volumes:
      - ./app/src:/app/src
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      API_URL: http://app:8000
    ports:
      - "8501:8501"
    depends_on:
      - app
    networks:
      - app-network

  web-proxy:
    build: ./web-proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_volume:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  ollama-init:
    image: ollama/ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: ["ollama", "pull", "tinyllama"]
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network
    restart: "no"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    restart: on-failure
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  database:
    image: postgres:16
    env_file:
      - ./app/.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

volumes:
  postgres_volume:
  rabbitmq_volume:
  ollama_volume:

networks:
  app-network:
    driver: bridge
